project_id = "fcptrpgqkjffgeddajwl"

[functions.tesla-auth]
verify_jwt = false

[functions.enphase-auth]
verify_jwt = false

[functions.enphase-data]
verify_jwt = false

[functions.tesla-devices]
verify_jwt = false

[functions.enphase-devices]
verify_jwt = false

[functions.claim-devices]
verify_jwt = false

[functions.tesla-data]
verify_jwt = false

[functions.calculate-rewards]
verify_jwt = false

[functions.tesla-register]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.solaredge-auth]
verify_jwt = false

[functions.solaredge-data]
verify_jwt = false

[functions.wallbox-auth]
verify_jwt = false

[functions.wallbox-data]
verify_jwt = false
