project_id = "fcptrpgqkjffgeddajwl"

[functions.tesla-auth]
verify_jwt = false

[functions.enphase-auth]
verify_jwt = false

[functions.enphase-data]
verify_jwt = false

[functions.tesla-devices]
verify_jwt = false

[functions.enphase-devices]
verify_jwt = false

[functions.claim-devices]
verify_jwt = false